<div class="entry-edit">
    <div id="reward_add_block">
        <form
        action="<?= $block->escapeHtml(
            $block->getUrl('rewardsystem/category/massRewardPointSpecific')
        ) ?>" enctype="multipart/form-data"
          method="post" id="formmassaddcategory">
            <?= /* @escapeNotVerified */ $block->getBlockHtml('formkey')?>
            <input type="hidden" name="wk_categoryids" id="wk_categoryids" value="" />
            <fieldset class="fieldset admin__fieldset">
                <div class="messages"></div>
                <div class="field admin__field">
                    <label class="label" for="rewardpoint">
                        <span><?= /* @escapeNotVerified */$block->escapeHtml(__('Enter Points'))?></span>
                    </label>
                    <div class="control">
                        <input id="rewardpoint" name="rewardpoint" type="text" class="input-text" />
                    </div>
                </div>
                <div class="field admin__field">
                    <label class="label" for="start_time">
                        <span><?= /* @escapeNotVerified */$block->escapeHtml(__('Start Time'))?></span>
                    </label>
                    <div class="control">
                        <input id="wk_start_time" name="start_time" type="text" class="input-text" />
                    </div>
                </div>
                <div class="field admin__field">
                    <label class="label" for="end_time">
                        <span><?= /* @escapeNotVerified */$block->escapeHtml(__('End Time'))?></span>
                    </label>
                    <div class="control">
                        <input id="wk_end_time" name="end_time" type="text" class="input-text" />
                    </div>
                </div>
                <div class="field admin__field">
                    <label class="label" for="status">
                        <span>
                          <?= $block->escapeHtml(__('Reward Point Status'))?>
                        </span>
                    </label>
                    <div class="control">
                        <select id="status" name="status" type="text" class="input-text required-entry">
                            <option value=0 selected="selected"><?= $block->escapeHtml(__('Disable'))?></option>
                            <option value=1><?= $block->escapeHtml(__('Enable'))?></option>
                        </select>
                    </div>
                </div>
                <button type="button" id="save_butncategory"
                title="<?= $block->escapeHtml(__('Update point for category')) ?>">
                <span><span>
                  <span><?= $block->escapeHtml(__('Update Points')) ?></span>
                </span></span>
              </button>
            </fieldset>
        </form>
    </div>
</div>
<?= /* @escapeNotVerified */ $block->getGridHtml(); ?>
<?php
    $blockGrid = $block->getBlockGrid();
    $gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php
$formData = [
    'wk_categoryids'    =>    '#wk_categoryids',
    'save_butncategory'    =>    '#save_butncategory',
    'massupdateformcategory'    => '#formmassaddcategory',
    'categorySubmitButton'    =>    '.submit_button',
];
$serializedFormData = $block->getLayout()->createBlock(
    \Webkul\RewardSystem\Block\RewardData::class
)->getJsonHelper()->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "WkRewardsystem": <?= /* @escapeNotVerified */$block->escapeJsQuote($serializedFormData); ?>
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_RewardSystem/js/assign-categoryspecific": {
                "gridJsObjectName": <?= /* @escapeNotVerified */  '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    // require('mage/apply/main').apply();
</script>
