<div class="entry-edit">
    <div id="reward_add_block">
        <form
        action="<?= $block->escapeHtml(
            $block->getUrl('rewardsystem/product/massRewardPoint')
        ) ?>" enctype="multipart/form-data" method="post" id="formmassadd">
            <?= /* @escapeNotVerified */ $block->getBlockHtml('formkey')?>
            <input type="hidden" name="wkproductids" id="wkproductids" value="" />
            <fieldset class="fieldset admin__fieldset">
                <div class="messages"></div>
                <div class="field admin__field">
                    <label class="label" for="rewardpoint">
                        <span><?= /* @escapeNotVerified */$block->escapeHtml(__('Enter Points'))?></span>
                    </label>
                    <div class="control">
                        <input id="rewardpoint" name="rewardpoint" type="text" class="input-text" />
                    </div>
                </div>
                <div class="field admin__field">
                    <label class="label" for="status">
                        <span><?= $block->escapeHtml(__('Reward Point Status'))?></span>
                    </label>
                    <div class="control">
                        <select id="status" name="status" type="text" class="input-text required-entry">
                            <option value=0 selected="selected"><?= $block->escapeHtml(__('Disable'))?></option>
                            <option value=1><?= /* @escapeNotVerified */ $block->escapeHtml(__('Enable'))?></option>
                        </select>
                    </div>
                </div>
                <button type="button" id="save_butn"
                title="<?= $block->escapeHtml(__('Update point for product'))?>" >
                <span><span>
                  <span><?= $block->escapeHtml(__('Update Points')) ?></span>
                </span></span>
              </button>
            </fieldset>
        </form>
    </div>
</div>
<?= /* @escapeNotVerified */ $block->getGridHtml() ?>
<?php
    $blockGrid = $block->getBlockGrid();
    $gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php
$formData = [
    'wkproductids'    =>    '#wkproductids',
    'savebtn'    =>    '#save_butn',
    'massupdateform'    => '#formmassadd',
    'submitButton'    =>    '.submit_button',
];
$serializedFormData = $block->getLayout()->createBlock(
    \Webkul\RewardSystem\Block\RewardData::class
)->getJsonHelper()->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "WkRewardsystem": <?= /* @escapeNotVerified */ $block->escapeJsQuote($serializedFormData); ?>
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_RewardSystem/js/assign-product": {
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
