<?php
$detailsArr = $block->getTransactiondetail();
$mhelper = $block->getHelperMagento();
// echo "<pre>";
// print_r($detailsArr);
// die;
//echo count($detailsArr);

//if (!empty($detailsArr)) {
if (!empty($detailsArr['allDetail']))
{
  $alldata=$detailsArr['allDetail'];
  $restInformation=$detailsArr['restInformation'];
    ?>

       <div class="">
         <div class="page-title-wrapper">
        <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">Order # <?php echo $alldata[0]['attributes']['salesOrderCode']?></span>    </h1>
            <?php
      if(!empty($restInformation)){
        if($restInformation['attributes']['currencyCode']=='GBP'){
          $currencycode='£';
        }else if($restInformation['attributes']['currencyCode']=='USD'){
          $currencycode='$';
        }else if($restInformation['attributes']['currencyCode']=='EURO'){
          $currencycode='€';
        }else{
          $currencycode='';
        }
        $date= substr($restInformation['attributes']['dateCreated'],0,10);
        $formtaed= explode("-",$date);
        //echo $formtaed[2]."/".$formtaed[1]."/".$formtaed[0];
        ?>
        <div class="order-date">
            <span class="label">Order Date:</span> <date><?php echo $formtaed[2]."/".$formtaed[1]."/".$formtaed[0]; ?></date></div>

        <!-- <p><?php //echo $formtaed[2]."/".$formtaed[1]."/".$formtaed[0]; ?></p> -->
          <span class="order-status"><?php echo $restInformation['attributes']['orderStatus']; ?></span><br>
          <span class="order-status">Customer PO: <?php
          if(array_key_exists("poCode",$restInformation['attributes'])){
            echo $restInformation['attributes']['poCode'];
          }else{
            echo '';
          }
          ?></span>


        <?php
      }
      // die;
       ?>
        </div>

    <ul class="items order-links"><li class="nav item current"><strong>Items Ordered</strong></li></ul><div class="order-details-items ordered">

        <div class="order-title">
            <strong>Items Ordered</strong>
        </div>

        <div class="table-wrapper order-items">
            <table class="data table table-order-items" id="my-orders-table" summary="Items Ordered">
                <caption class="table-caption">Items Ordered</caption>
                <thead>
                    <tr>
                        <th class="col name">Product Name</th>
                        <th class="col sku">SKU</th>
                        <th scope="col">Sale Price</th>
                        <th scope="col">Net Price</th>
                        <th scope="col">Qty</th>
                        <th scope="col">Ext Price</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    // if (is_array($result_detail_1) && count($result_detail_1)>0) {
                         $subtotal=0;
                         for($i=0;$i<count($alldata);$i++){
                            ?>
                    <tr id="order-item-row-1">
                        <td class="col name" data-th="Product Name">
                            <strong class="product name product-item-name"><?php echo $alldata[$i]['attributes']['itemDescription'];?></strong>
                        </td>
                        <td class="col sku" data-th="SKU"><?php echo $alldata[$i]['attributes']['sku'];?></td>
                        <td class="col price" data-th="Price">
                          <?php echo $currencycode.number_format((float)$alldata[$i]['attributes']['salesPriceRate'], 2, '.', ',');?>
                        </td>
                        <td class="col price" data-th="Price">
                          <?php echo $currencycode.number_format((float)$alldata[$i]['attributes']['netPriceRate'], 2, '.', ',');?>
                        </td>

                        <td class="col qty" data-th="Qty">
                            <ul class="items-qty">
                                <li class="item">
                                    <span class="title">Ordered</span>
                                    <span class="content"><?php echo $alldata[$i]['attributes']['quantityOrdered'];?></span>
                                </li>
                            </ul>
                        </td>
                        <td class="col price" data-th="Price">
                          <?php echo $currencycode.number_format((float)$alldata[$i]['attributes']['extPriceRate'], 2, '.', ',');?>
                        </td>
                    </tr>
                        <?php } ?>
                </tbody>

                <tfoot>
                    <tr class="subtotal">
                        <th colspan="5" class="mark" scope="row">
                            Subtotal                    </th>
                        <td class="amount" data-th="Subtotal">
                            <span class="price"><?php echo $currencycode.number_format((float)$restInformation['attributes']['subTotalRate'], 2, '.', ','); ?></span>                    </td>
                    </tr>
                    <tr class="shipping">
                        <th colspan="5" class="mark" scope="row">
                            Shipping &amp; Handling                    </th>
                        <td class="amount" data-th="Shipping &amp; Handling">
                            <span class="price"><?php echo $currencycode.number_format((float)$restInformation['attributes']['freightRate'], 2, '.', ','); ?></span>                    </td>
                    </tr>
                    <tr class="shipping">
                        <th colspan="5" class="mark" scope="row">
                           VAT                   </th>
                        <td class="amount" data-th="Tax">
                            <span class="price"><?php echo $currencycode.number_format((float)$restInformation['attributes']['taxRate'], 2, '.', ','); ?></span></td>
                    </tr>
                    <tr class="grand_total">
                        <th colspan="5" class="mark" scope="row">
                            <strong>Grand Total</strong>
                        </th>
                        <td class="amount" data-th="Grand Total">
                            <strong><span class="price"><?php echo $currencycode?><?php echo number_format((float)$restInformation['attributes']['totalRate'], 2, '.', ',');?></span></strong>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="block block-order-details-view">
            <div class="block-title">
                <strong>Order Information</strong>
            </div>
            <div class="block-content">
                <div class="box box-order-shipping-address">
                    <strong class="box-title"><span>Shipping Address</span></strong>
                    <div class="box-content">

                        <address><?php echo $restInformation['attributes']['shipToName']?><br>

                            <?php echo $restInformation['attributes']['shipToAddress']?><br>



                            <?php echo $restInformation['attributes']['shipToCity']?>,  <?php echo $restInformation['attributes']['shipToPostalCode'] ?><br>
                            <?php echo $restInformation['attributes']['shipToCountry']?><br>


                        </address>
                    </div>
                </div>

                <div class="box box-order-shipping-method">
                    <strong class="box-title">
                        <span>Shipping Method</span>
                    </strong>
                    <div class="box-content">
                        <?php echo $restInformation['attributes']['shippingMethodCode']?>                      </div>
                </div>

                <div class="box box-order-billing-address">
                    <strong class="box-title">
                        <span>Billing Address</span>
                    </strong>
                    <div class="box-content">
                        <address><?php echo $restInformation['attributes']['billToName']?><br>

                            <?php echo $restInformation['attributes']['billToAddress']?><br>



                            <?php echo $restInformation['attributes']['billToCity']?>,  <?php echo $restInformation['attributes']['billToPostalCode'] ?><br>
                            <?php echo $restInformation['attributes']['billToCountry']?><br>


                        </address>
                    </div>
                </div>
                <div class="box box-order-billing-method">
                    <strong class="box-title">
                        <span>Payment Method</span>
                    </strong>
                    <div class="box-content">
                        <dl class="payment-method">
                            <dt class="title"><?php echo $restInformation['attributes']['paymentTermCode']?></dt>
                        </dl>
                    </div>
                </div>
            </div>
        </div>

        <div class="actions-toolbar">
            <div class="secondary">
                <a class="action back" href="http://127.0.0.1/magento224/index.php/sales/order/history/">
                    <span>Back to My Orders</span>
                </a>
            </div>
        </div>
    </div>

    <input name="form_key" type="hidden" value="NFKcfAdFfAWHxLAr"><div id="authenticationPopup" data-bind="scope:'authenticationPopup'">
        <script>
            window.authenticationPopup = {"autocomplete": "off", "customerRegisterUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/customer\/account\/create\/", "customerForgotPasswordUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/customer\/account\/forgotpassword\/", "baseUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/", "customerCheckoutUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/checkout\/#shipping"};
        </script>
        <!-- ko template: getTemplate() -->


        <!-- /ko -->

    </div>




</div>
<?php
} else{
?>
    <div class=""><div class="page-title-wrapper">
        <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">Sorry something wrong order not found!!</span>    </h1>
        </div>
        <input name="form_key" type="hidden" value="NFKcfAdFfAWHxLAr"><div id="authenticationPopup" data-bind="scope:'authenticationPopup'">
        <script>
            window.authenticationPopup = {"autocomplete": "off", "customerRegisterUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/customer\/account\/create\/", "customerForgotPasswordUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/customer\/account\/forgotpassword\/", "baseUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/", "customerCheckoutUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/checkout\/#shipping"};
        </script>
        <!-- ko template: getTemplate() -->


        <!-- /ko -->

    </div>
    </div>
<?php } ?>
