<?php
/**
 * Provider: Meetanshi.
 * Package: Meetanshi VatExempt
 * Support: support@meetanshi.com (https://meetanshi.com/)
 */
?>
<?php $order = $block->getCustomerDeclaration(); ?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Vat Exempt Declaration') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="box-content">
            <?php echo $order ?>
        </div>
    </div>
</section>

