
<?php
$blockObj= $block->getLayout()->createBlock('PurpleCommerce\Custom\Block\Index');
$blockObj->flushCache();
$isfromFeed=false;
if($_SERVER['QUERY_STRING']){
    // echo '-->'.$_SERVER['QUERY_STRING'];
    $isfromFeed = true;
}


// @codingStandardsIgnoreFile

/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */



/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */

$priceModel = $block->getPriceType('regular_price');



/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */

$finalPriceModel = $block->getPriceType('final_price');

$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';

$schema = ($block->getZone() == 'item_view') ? true : false;

?>
<?php $show = 0;
?>




<?php if ($block->hasSpecialPrice()): ?>
    <?php //$show = 0;?>
    <span class="old-price sly-old-price" id="pc-old" style="display:none">

        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [

            'display_label'     => __('Starts From1'),

            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),

            'price_type'        => 'oldPrice',

            'include_container' => true,

            'skip_adjustments'  => true

        ]); ?>
        <?php 
            if($show==0){
                echo '<br><span class="label-start">Starts From</span>';
                $show++;
            }
        ?>
    </span>
    

<?php endif; ?>





<span class="normal-price" id="pc-normal" style="display:none">

            
    <?php

    $arguments = [

        'display_label' => __('Starts From'),

        'price_id' => $block->getPriceId('product-price-' . $idSuffix),

        'price_type' => 'finalPrice',

        'include_container' => true,

        'schema' => $schema,

    ];

    /* @noEscape */ echo $block->renderAmount($finalPriceModel->getAmount(), $arguments);

    ?>

</span>





<?php if ($block->showMinimalPrice()): ?>

    <?php if ($block->getUseLinkForAsLowAs()):?>

        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">

            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>

        </a>

    <?php else:?>

        <span class="minimal-price-link">

            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>

        </span>

    <?php endif?>

<?php endif; ?>
<script>
require(['jquery','domReady!'], function ($) {
    $(document).on('click','.swatch-option',function(){

        // alert("clicked");
        $('.label-start').hide();
    });
    $( document ).ready(function() {
        
        // $('#pc-old').html('');
        var check = '<?php echo $isfromFeed;?>';
        // console.log("check->",check);
        if(check){
            setTimeout(() => {
                // $('.normal-price').html('');
                $('#pc-normal').show();
                $('#pc-old').show();
            }, 2000);
            
        }else{
            $('#pc-normal').show();
            $('#pc-old').show();
        }
    });
});
</script>