<?php
/**
 * @category   Webkul
 * @package    Webkul_GoogleShoppingFeed
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */

    $productCount = $block->getImportedProduct();
?>
<fieldset class="fieldset">
    <div class="wk-mu-note wk-mu-box">
        <?= /* @noEscape */ __('Starting Execution'); ?>...
    </div>
    <div class="wk-mu-notice wk-mu-box">
        <?= /* @noEscape */ __("Please don't close or refresh the window while exporting product(s)."); ?>
    </div>
    <div class="wk-mu-success wk-mu-box">
        <?= /* @noEscape */ __('Total %1 product(s) to export.', $productCount); ?>
    </div>
    <?php if ($productCount > 0): ?>
        <div class="wk-mu-info-bar">
            <?= /* @noEscape */ __('Exporting '); ?>
            <span class="wk-current">1</span><?= /* @noEscape */ __(' of %1', $productCount);?>
            <?php $loaderImg = $block->getViewFileUrl('Webkul_GoogleShoppingFeed::images/loader.gif') ?>
            <img id="loader-image" src="<?= /* @noEscape */ $loaderImg ?>" />
        </div>
        <div class="wk-mu-progress-bar">
            <div class="wk-mu-progress-bar-current"></div>
        </div>
    <?php else: ?>
        <div class="wk-mu-note wk-mu-box">
            <?= /* @noEscape */ __('No product to export.'); ?>
        </div>
        <div class="wk-mu-note wk-mu-box">
            <?= /* @noEscape */ __('Finsihed Execution.'); ?>
        </div>
    <?php endif; ?>
    <div class="product_create_error_msg"></div>
</fieldset>
<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document).ready(function() {
            var skipCount = 0;
            var exportUrl = "<?= /* @noEscape */ $block->getUrl('googleshoppingfeed/products/export'); ?>";
            var total = <?= /* @noEscape */ $productCount; ?>;
            if(total > 0) {
                exportProduct(0, 0);
            }
            function exportProduct(count, skipCount)
            {
                count = count;
                $.ajax({
                    type: 'post',
                    url:exportUrl,
                    async: true,
                    dataType: 'json',
                    data : { 'count':count, 'skip':skipCount, "form_key" : window.FORM_KEY},
                    success:function(data) {
                        if(data['error'] == 1) {
                            $(".product_create_error_msg").prepend($('<div />')
                                                    .addClass('message message-error error')
                                                    .text(data['message'])
                                                );
                            skipCount++;
                        }
                        count = count+data['total'];
                        width = (100/total)*count;
                        $(".wk-mu-progress-bar-current").animate({width: width+"%"},'slow', function() {
                            if(count >= total) {
                                finishImporting(count, skipCount);
                                $(".wk-mu-info-bar").text("<?= /* @noEscape */ __('Completed') ?>");
                            } else {
                                $(".wk-current").text(count);
                                exportProduct(count, skipCount);
                            }
                        });
                    }
                });
            }

            function finishImporting(count, skipCount)
            {
                $.ajax({
                    type: 'POST',
                    url:exportUrl,
                    async: true,
                    dataType: 'json',
                    data : {count:count,skip:skipCount,finish:true,form_key : window.FORM_KEY},
                    success:function(data) {
                        if (!data['error']) {
                            $(".fieldset").append(data['message']);
                        } else {
                            $(".product_create_error_msg").prepend($('<div />')
                                                    .addClass('message message-error error')
                                                    .text(data['message'])
                                                );
                        }
                    }
                });
            }
        });
    });
</script>
